# Travis CI
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
matrix:
  include:
    - # Ruby 1.9
      rvm: 1.9
      env: BUNTO_VERSION=1.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - BUNTO_VERSION=1.0
cache: bundler
sudo: false
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - bundle update
script: ./script/cibuild
notifications:
  email: false
