# Travis CI
language: ruby
rvm:
  - 2.3.1
  - 2.3.0
  - 2.2.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - BUNTO_VERSION=3.0.0
    - BUNTO_VERSION=3.2.1
cache: bundler
sudo: false
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - bundle update
script: ./script/cibuild
notifications:
  email: false
